### ISSUE TITLE
add Keras/klab-13-3-mnist_save_restore.py

### ISSUE THREAD

**Issue by skyer9** [hunkim/DeepLearningZeroToAll#141]
https://gist.github.com/skyer9/d4cc48e7e0182f198a8b8d1a388f248f

this file describes how to save/load model.

**Comment by kkweon** [comment]
Looks good.
But in Keras, it's preferred to use full model save/load instead of saving/loading weights.

* Full model save/load for regular jobs
* Weight save/load is specifically designed for transfer learning.

The reason for this preference is that 
1. we don't have to define a model architecture when we use a full model load.
2. model epoch is taken care of automatically. For advanced optimizers like Adam, RMSProp, it's important to keep the number of steps.

So, I think it's a good idea to write a few comments about each method.

```python
from keras.models import load_model

#save
model.save(filepath) # instead of model.save_weights()

#load
model = load_model(filepath) # instead of model.load_weights()
```

**Comment by skyer9** [comment]
in Keras, simple is best.
you're suggestion is good.
i will look you're suggestion.
