### ISSUE TITLE
lab-11-2-mnist_deep_cnn The output of Fully-connected layer1

### ISSUE THREAD

**Issue by piplyman** [hunkim/DeepLearningZeroToAll#199]
Why does Fully-connected layer1 have 625 output?

**Comment by kkweon** [comment]
Hi, your question is ambiguous. So I will try my best to answer your question.


### Why does it have 625 output?
Because in the [previous line](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-11-2-mnist_deep_cnn.py#L79),
```python
# W4.shape = (128 * 4 * 4, 625)
W4 = tf.get_variable("W4", shape=[128 * 4 * 4, 625],
                     initializer=tf.contrib.layers.xavier_initializer())
```
So the shape of `X * W4` will be (?, 625) where `X` is the previous output of shape (?, 128 * 4 * 4)

### Why is it set to 625?
It doesn't have to be 625 because it's a hyperparameter. It just happens to be in this case.
